export const CHALLENGE_CATEGORY = [
    {value: null, label: 'All categories'},
    {value: 9, label: 'General Knowledge'},
    {value: 10, label: 'Books'},
    {value: 11, label: 'Films'},
    {value: 12, label: 'Music'},
    {value: 13, label: 'Musicals and Theaters'},
    {value: 14, label: 'Television'},
    {value: 15, label: 'Video Games'},
    {value: 16, label: 'Board Games'},
    {value: 17, label: 'Science and Nature'},
    {value: 18, label: 'Computers'},
    {value: 19, label: 'Mathematics'},
    {value: 20, label: 'Mythology'},
    {value: 21, label: 'Sports'},
    {value: 22, label: 'Geography'},
    {value: 23, label: 'History'},
    {value: 24, label: 'Politics'},
    {value: 25, label: 'Art'},
    {value: 26, label: 'Celebrities'},
    {value: 27, label: 'Animals'},
    {value: 28, label: 'Vehicles'},
    {value: 29, label: 'Comic Books'},
    {value: 30, label: 'Gadgets'},
    {value: 31, label: 'Japanese Anime and Manga'},
    {value: 32, label: 'Cartoons and Animations'},
];


export const DIFFICULTY = [
    {value: null, label: 'All Difficulties'},
    {value: 'easy', label: 'Easy'},
    {value: 'medium', label: 'Medium'},
    {value: 'hard', label: 'Hard'},
];
